

spring.datasource.url= jdbc:postgresql://ec2-44-207-133-100.compute-1.amazonaws.com:5432/d12gvgobf5om12
spring.datasource.username= xwamduyadvhmaf
spring.datasource.password= f7aac03aa67db12649d8afacadabf9444d2238d5353b4912a63b3e9e09fa6684