#spring.datasource.url= jdbc:postgresql://localhost:5432/aws-blog-app

spring.datasource.url= jdbc:postgresql://localhost:5432/blog-app
spring.datasource.username= postgres
spring.datasource.password= root