#spring.datasource.url= jdbc:postgresql://sushrut-e-journal.cbtc2v8t7cfp.us-east-1.rds.amazonaws.com:5432/e_journal_app
#spring.datasource.username= sushrut
#spring.datasource.password= rootroot


spring.datasource.url= jdbc:postgresql://ec2-52-200-5-135.compute-1.amazonaws.com:5432/dal9lmj11j7ph9
spring.datasource.username= lgzcryufrqqmhh
spring.datasource.password= 540ad79d39342bbd69cfb9f015d8ac49e42fbfe9a8109a4448f6dbdbfd7240ff