server.port=5000

#spring.datasource.url= jdbc:postgresql://localhost:5432/blog-app
#spring.datasource.username= postgres
#spring.datasource.password= root
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

project.image=images/

logging.level.org.springframework.security= DEBUG 

#spring.security.user.name = sushrut
#spring.security.user.password= root
#
#spring.security.user.roles= ADMIN

#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true


spring.profiles.active= prod